### ISSUE TITLE
Wavin AHC9000 component fails to compile on ESPHome 2024–2026 due to removed Sensor API methods

### ISSUE THREAD

**Issue by Icarus81** [heinekmadsen/esphome_components#83]
**Description:**

The Wavin AHC9000 component fails to compile on all ESPHome versions released after the 2024 API changes. The generated main.cpp still calls deprecated methods such as set_device_class() and set_unit_of_measurement(), which were removed from the Sensor API in ESPHome 2024.2+ and fully removed in ESPHome 2026.3.0.

This makes the component incompatible with all current ESPHome releases.

**Error log:**
```
error: 'class esphome::sensor::Sensor' has no member named 'set_device_class'
error: 'class esphome::sensor::Sensor' has no member named 'set_unit_of_measurement'
```

**Root cause**
ESPHome removed the following methods from Sensor:
```
set_device_class()
set_unit_of_measurement()
```

They were replaced by new buffer‑based methods such as:
```
get_device_class_to()
get_icon_to()
```

The Wavin component still uses the old API and therefore cannot compile on any modern ESPHome version.

**Expected behavior**
The component should compile successfully on current ESPHome versions (2024–2026) without requiring users to downgrade ESPHome or keep outdated firmware on their devices.

**Suggested fix**
Update the component to use the new Sensor API. Specifically:
Remove all calls to set_device_class() and set_unit_of_measurement()
Replace them with the new metadata system introduced in ESPHome 2024+
Ensure all sensor entities expose correct device class and unit via the new API
If needed, I can help test updated code on real Wavin AHC9000 hardware.

**Environment**
ESPHome: 2026.3.3
Hardware: ESP8266 (NodeMCU v2)
Component: Wavin AHC9000 (from this repository)
Issue reproducible: Always

**Additional context**
The component used to compile successfully on my device, but after updating ESPHome fraom 2026.2 to 2026.3, the build now fails due to removed Sensor API methods. The issue is not related to caching or configuration changes on my side — the component code itself still calls deprecated methods that no longer exist in ESPHome 2024–2026. Updating these API calls should restore compatibility.
